### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by Jenselme**
- Add python 3.3 and 3.4 to travis
- Update dependencies
- Adapt code

### CODE REVIEW

**Comment by rammie** [comment]
Thanks for this pull request! I really wanted to do this earlier, but didn't get around to it since a package we depended on (fdfgen I think) was not python 3 compatible.

Anyway, can you look into why the tests are failing? As soon as they pass, I will merge it in and cut a new release. If you haven't already, could you also run style checks with flake8. Though that is minor, I could always make another commit fixing any style issues once your PR is merged in.

**Comment by rammie** [comment]
Oops, you've left behind a hard coded path to your pdftk.

https://github.com/rammie/pdfjinja/pull/2/files#diff-ff0385fda4247e0f5e9888530c62c6b4R204

**Comment by Jenselme** [comment]
> Oops, you've left behind a hard coded path to your pdftk.

Yeah, I did a quick modification to fix the tests and forgot to remove that. Fixed.

Python2 tests are good: https://travis-ci.org/rammie/pdfjinja/jobs/125013600

Python3 test are failing due to https://github.com/ccnmtl/fdfgen/issues/12 which I solve in https://github.com/ccnmtl/fdfgen/pull/14 I will post a comment here once the PR is merged.

**Comment by Jenselme** [comment]
Just updated fdfgen to 0.13.0 to fix the bug with Python3. All tests now pass.

**Comment by Jenselme** [comment]
Can we have a new release with Python3 support?

**Pull request merged**
